### ISSUE TITLE
Accordion creationPolicy="all" makes all elements initially visible

### ISSUE THREAD

**Issue by neminovno** [tinklondon/Tink-Flex-4.15#1]
In Tink-Flex-4.15 version of Accordion, is there still a bug with creationPolicy="all" ?
I don't know exactly which version I used, but when having two elements with accordions creationPolicy set to "all", second element is also visible initially, although first element is selected.

BTW Thank you for your work.

**Comment by neminovno** [comment]
Hm... Commit 9bdb7447884fd001ba9aa75ec64cb2094737e6ab could have fixed this issue? As I understand the commit, it would "refresh" accordion if elements are added dynamically, and it would hide non-selected elements?

**Comment by neminovno** [comment]
Now I got some new bug: If I have 2 elements in Accordion, and second one is selected/visible. After setting some text value inside first element, first element becomes visible behind opened second element.

**Comment by tinklondon** [comment]
Hi neminovna

Commit  9bdb744 was to ensure that change events were dispatched from the NavigatorGroup so that it acts inline with an IList (as it implements IList can be used as a source of databinding). This fix was to address a bug I noticed when I had some localization taking place on the label property of a child. I noticed that when the label was updated, the ButtonBar that used the NavigatorGroup as a dataProvider, didn't update its label, and that was because it didn't receive any notification that anything had changed.

It would be great if you could give me simple examples of the bugs.

I can't promised how soon I could look at them, but I will try and look into it when I can.

**Comment by neminovno** [comment]
Hi tinklondon

Thanks for info. Great news about label property. That means it would be easier to localize without labelFunction?

About issue, what I am doing is actually moving elements from navigator to accordion:
accordion.addElement(navigator.removeElementAt(0));
accordion.addElement(navigator.removeElementAt(0)); 
and that is probably what makes second element invisible in accordion. Is that the best way to do it?

I will try to create small test case when both elements are visible at same time.

**Comment by tinklondon** [comment]
Your along the same kind of lines but even if you had a labelFunction, it wouldn't have worked when the locale changes, as the ButtonBar wouldn't know anything had changed, and therefore wouldn't re-run the labelFunction. With the events being dispatched from the navigators, this issue is now resolved.

Yeah if you could knock up a super simple example, that would be great.

**Comment by neminovno** [comment]
I initially reported issue in wrong project. I am using 4.6 version, not 4.15 
Is that localization fix applied also in https://github.com/tinklondon/Tink-Flex-4.6 ?

**Comment by tinklondon** [comment]
No, that fix is only in 4.15.

I wouldn't have thought that would affect the issue you are seeing though.
